prod:

all:
  handler:
    class:                   fpErrorNotifierHandler  
        
  message:
    class:                   fpErrorNotifierMessage
    
  helper: 
    class:                   fpErrorNotifierMessageHelper
    
  decorator:
    class:                   fpErrorNotifierDecoratorHtml
  
  driver: 
    class:                   fpErrorNotifierDriverNull
    options:                 {}
#  
# EXAMPLES OF DRIVER CONFIGURATION
#
# FILE DRIVER
#
#  driver:
#    class:                  fpErrorNotifierDriverFile
#    options:        
#      path:                 '%SF_LOG_DIR%/last-error.html'
# 
# OR MAIL NATIVE DRIVER
#
#  driver:
#    class:                  fpErrorNotifierDriverMailNative
#    options:
#      to:                   developer1@example.com,developer2@example.com
#      from:                 mail-from@example.com
#  
#
#  EXAMPLE OF IGNORE HANDLER
#
#  handler:
#    class:                   fpErrorNotifierHandlerIgnore
#    options:
#      ignore_errors:
#        <?php echo E_ERROR ?>:             false
#        <?php echo E_WARNING ?>:           false
#        <?php echo E_PARSE ?>:             false
#        <?php echo E_NOTICE ?>:            true
#        <?php echo E_CORE_ERROR ?>:        false
#        <?php echo E_CORE_WARNING ?>:      false
#        <?php echo E_COMPILE_ERROR ?>:     false
#        <?php echo E_COMPILE_WARNING ?>:   false
#        <?php echo E_USER_ERROR ?>:        true
#        <?php echo E_USER_WARNING ?>:      true
#        <?php echo E_USER_NOTICE ?>:       true
#        <?php echo E_STRICT ?>:            true
#        <?php echo E_RECOVERABLE_ERROR ?>: true
#        <?php echo E_DEPRECATED ?>:        true
#        <?php echo E_USER_DEPRECATED ?>:   true
#        <?php echo E_ALL ?>:               true
#      ignore_exceptions:     [FooException]
#      log_ignored:           true